### ISSUE TITLE
Relicense to allow usage of source code without disclosure.

### ISSUE THREAD

**Issue by vxern** [vxern/synadart#1]
The MIT or Apache licences would be more appropriate than GPL.

**Comment by dbravender** [comment]
I would really appreciate a license change. I need a neural net library for some games I'm writing and I don't want to open source my games but I would contribute new code and fixes for production use of this library if it was licensed under MIT or Apache.

**Comment by vxern** [comment]
> I would really appreciate a license change. I need a neural net library for some games I'm writing and I don't want to open source my games but I would contribute new code and fixes for production use of this library if it was licensed under MIT or Apache.

Unfortunately, I don't think this library could be used in production. It lacks many features, and the only reason I created it in the first place was to learn the fundamentals of neural networks myself. 😅 Plus the fact that the available implementations weren't created with readability in mind as much as functionality.

Thanks for the comment, though! I completely forgot about following up on this issue. I'll get to it right away. 😄

**Comment by vxern** [comment]
Resolved in 9dcb729.
